### ISSUE TITLE
The compatibility between this framework and snooboy is very poor, which will lead to the startup failure of snooboy

### ISSUE THREAD

**Issue by baihua86** [samuelhwilliams/Eel#237] opened 2020-02-01 09:08 UTC
**Describe the problem**
A clear and concise description of what you're trying to accomplish, and where you're having difficulty.

**Code snippet(s)**

```python
import eel

...
```

```html
<html>
   ...
</html>
```

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by samuelhwilliams** [comment] 2020-02-02 17:40
Duplicate of #236

**Closed by samuelhwilliams** 2020-02-02 17:40 UTC
Labels: help wanted
