### ISSUE TITLE
Jinja2 example not working

### ISSUE THREAD

**Issue by A1S0N** [samuelhwilliams/Eel#189] opened 2019-09-20 00:20 UTC
{% extends 'base.html' %} {% block title %}Hello, World!{% endblock %} {% block head_scripts %} eel.expose(say_hello_js); // Expose this function to Python function say_hello_js(x) { console.log("Hello from " + x); } eel.expose(js_random); function js_random() { return Math.random(); } function print_num(n) { console.log('Got this from Python: ' + n); } eel.py_random()(print_num); say_hello_js("Javascript World!"); eel.say_hello_py("Javascript World!"); // Call a Python function {% endblock %} {% block content %} Hello, World! 
Page 2 {% endblock %}

**Comment by mrunion** [comment] 2019-09-26 15:08
There was a post earlier about changing the "jinja_templates" parameter to just "templates". That works, BUT the example "hello.html" page still doesn't. If you remove the JavaScript from that page it will work -- but you may have to clear your browser's cache (or use the eel.start parameter "disable_cache=True"). I am trying to find out what JavaScript cannot be put inline in the code like the sample shows....

**Comment by paulbaumgarten** [comment] 2019-09-28 06:05
Thanks I had the same issue. The fix by @mrunion works. I don't suppose anyone has worked out how to pass context data to Jinga?

**Comment by samuelhwilliams** [comment] 2019-10-03 08:59
Duplicate of #187

**Closed by samuelhwilliams** 2019-10-03 08:59 UTC
