### ISSUE TITLE
video streaming using eel

### ISSUE THREAD

**Issue by samilajuneed** [samuelhwilliams/Eel#260] opened 2020-03-21 06:40 UTC
sir can u give me some example how the web cam video can stream in to eel project

**Comment by RahulBadenkal** [comment] 2020-03-26 07:00
Duplicate of #193

**Comment by samuelhwilliams** [comment] 2020-03-26 10:05
Hopefully the above issue helps you @samilajuneed :)

**Closed by samuelhwilliams** 2020-03-26 10:05 UTC
