### ISSUE TITLE
Handle reconnect to websocket if connection lost?

### ISSUE THREAD

**Issue by thelinuxdude** [samuelhwilliams/Eel#317] opened 2020-06-16 17:03 UTC
**Is your feature request related to a problem? Please describe.**
When a connection between the client websocket and the server are lost, say due to the networking going down.  From the UI side, I could not tell it was down until I made a call to an eel functions that was being exposed.  This fails with an "WebSocket is already in CLOSING or CLOSED state"

**Describe the solution you'd like**
I would like away to re-connect on a failure or indicate back to the UI that there was a failure.  I rather have it reconnect first before reporting any problems.

**Describe alternatives you've considered**
Not sure the best place to change in the eel.js to catch the issue and recover.

**Comment by samuelhwilliams** [comment] 2020-06-16 20:50
I suspect this is a duplicate of https://github.com/samuelhwilliams/Eel/issues/309 (even if not I'd probably look at them together). I will close this in lieu of #309.

**Closed by samuelhwilliams** 2020-06-16 20:50 UTC
Labels: enhancement
