### ISSUE TITLE
Canvas DrawImage not working on EEl

### ISSUE THREAD

**Issue by Deadpoolmine** [samuelhwilliams/Eel#360] opened 2020-07-17 06:18 UTC

**Comment by samuelhwilliams** [comment] 2020-07-26 20:00
I'm sorry, there's not really any information here to go on so I'm going to close this issue. If you're after help or think there's a bug we would really appreciate you including the code you're using so that we can confirm what the problem is.

**Closed by samuelhwilliams** 2020-07-26 20:00 UTC
Labels: bug
